image:
  repository: ghcr.io/thurbeen/thurkube
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

logLevel: info

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

crds:
  install: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
