image:
  repository: ghcr.io/thurbeen/thurkube
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

logLevel: info

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

crds:
  install: true

probes:
  enabled: true
  port: 8080
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
